# (from: https://github.com/codecov/example-node/blob/master/.travis.yml)
language: node_js
sudo: false
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
install:
  - npm install
script:
  # Build this project
  - npm run build
  # Install math2image to global
  - npm install -g .

  # ==== Just working-test ====

  # Output to stdout
  - echo "e^{i \pi} + 1 = 0" | math2image

  # From a file
  - math2image sample_texs/sample7.math.tex

  # from a file specifying output name
  - math2image -o output.svg sample_texs/sample7.math.tex

  # save as .png
  - math2image --to-png --png-width=500 sample_texs/sample7.math.tex

